### ISSUE TITLE
tagHelpers do not get used

### ISSUE THREAD

**Issue by dirkju** [sgjsakura/aspnet5#3] opened 2016-02-14 22:45 UTC
Hi,

I've installed your tagHelper nuget and added references for the tagHelper library to _ViewImports.cshtml like this:
```
@using Sakura.AspNet.Mvc.TagHelpers
@addTagHelper "*, Sakura.AspNet.Mvc.TagHelpers"

```
and in my view use it like this:
`<input type="checkbox" asp-flag-for="Options" asp-flag-value="MyOptions.Premium" class="form-control" />
`
but the renderer does not seem to pick it up. I can still see the (unresolved) asp-flags-for tags in the final html. I'm using Mvc 6.0.0-rc1.final. Is there anything else needed to make the tagHelpers work?

**Comment by sgjsakura** [comment] 2016-02-15 07:06
@dirkju Due to some reason,  the attribute name has changed in recent versions. I suggest you should use the lastest version i.e. "1.0.0-rc1-update3".  Could you tell me which version of this package are you using now?

**Comment by dirkju** [comment] 2016-02-15 20:36
I'm using the latest of your package (1.0.0-update3) already. When I copy the FlagsEnum tag helper and ModelBinder classes into my project and register - it works. Is there any initialization missing?

**Comment by sgjsakura** [comment] 2016-02-16 04:32
@dirkju HI, Unfortunately, I cannot reproduce your issue in my enviroment. Could you send me a demo project via email? That's may be helpful, thank you very much~

**Comment by sgjsakura** [comment] 2016-03-01 06:03
Closing the issue since the owner seems does not have any response. If you have further question, please feel free to reopen this issue or submit a new one.

**Closed by sgjsakura** 2016-03-01 06:03 UTC
